version: '3.9'
services:
  tooling_frontend:
    build: .
    volumes:
      - tooling_frontend:/var/www/html
    networks:
      - tooling_networks
    ports:
      - "8082:80"
    links:
      - "db"

  db:
    image: mysql:5.7
    hostname: database
    environment:
      MYSQL_DATABASE: toolingdb
      MYSQL_USER: tooling
      MYSQL_PASSWORD: password
      MYSQL_RANDOM_ROOT_PASSWORD: 1
    restart: always
    networks:
      - tooling_networks
    volumes:
      - db:/var/lib/mysql

networks:
  tooling_networks:
volumes:
  db:
  tooling_frontend:

